name: build java/stringtemplate_v/linux/4

on:
  push:
    branches:
      - 'java/stringtemplate_v/linux/4'
  pull_request:
    branches:
      - 'java/stringtemplate_v/linux/4'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone matching private source branch
        env:
          GH_TOKEN: ${{ secrets.COMPILER_PAT }}
        shell: bash
        run: |
          set -euo pipefail
          gh repo clone sandisks/github_codespaces_compile source -- --depth=1 --single-branch --branch "$GITHUB_REF_NAME"
      - name: Execute source script
        working-directory: source
        shell: bash
        run: |
          set -euo pipefail
          chmod +x -- 'java/stringtemplate4/linux/get_java_stringtemplate4_linux.sh'
          './java/stringtemplate4/linux/get_java_stringtemplate4_linux.sh'
