name: build cpp/re2/linux/2024_05_01

on:
  push:
    branches:
      - 'cpp/re2/linux/2024_05_01'
  pull_request:
    branches:
      - 'cpp/re2/linux/2024_05_01'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone matching private source branch
        env:
          GH_TOKEN: ${{ secrets.COMPILER_PAT }}
        shell: bash
        run: |
          set -euo pipefail
          gh repo clone sandisks/github_codespaces_compile source -- --depth=1 --single-branch --branch "$GITHUB_REF_NAME"
      - name: Execute source script
        working-directory: source
        shell: bash
        run: |
          set -euo pipefail
          chmod +x -- 'cpp/re2/linux/cpp_re2_linux_2024_05_01.sh'
          './cpp/re2/linux/cpp_re2_linux_2024_05_01.sh'
