name: build cpp/grpc/linux/1_28_1

on:
  push:
    branches:
      - 'cpp/grpc/linux/1_28_1'
  pull_request:
    branches:
      - 'cpp/grpc/linux/1_28_1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone matching private source branch
        env:
          GH_TOKEN: ${{ secrets.COMPILER_PAT }}
        shell: bash
        run: |
          set -euo pipefail
          gh repo clone sandisks/github_codespaces_compile source -- --depth=1 --single-branch --branch "$GITHUB_REF_NAME"
      - name: Execute source script
        working-directory: source
        shell: bash
        run: |
          set -euo pipefail
          chmod +x -- 'cpp/get_grpc1_28_1/linux/get_grpc1_28_1_linux.sh'
          './cpp/get_grpc1_28_1/linux/get_grpc1_28_1_linux.sh'
