name: build cpp/catch2/linux/3_5_2

on:
  push:
    branches:
      - 'cpp/catch2/linux/3_5_2'
  pull_request:
    branches:
      - 'cpp/catch2/linux/3_5_2'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone matching private source branch
        env:
          GH_TOKEN: ${{ secrets.COMPILER_PAT }}
        shell: bash
        run: |
          set -euo pipefail
          gh repo clone sandisks/github_codespaces_compile source -- --depth=1 --single-branch --branch "$GITHUB_REF_NAME"
      - name: Execute source script
        working-directory: source
        shell: bash
        run: |
          set -euo pipefail
          chmod +x -- 'cpp/catch2/linux/3_5_2/get_catch2.sh'
          './cpp/catch2/linux/3_5_2/get_catch2.sh'
