name: build c/apache_mynewt/linux/mynewt_1_15_0_tag

on:
  push:
    branches:
      - 'c/apache_mynewt/linux/mynewt_1_15_0_tag'
  pull_request:
    branches:
      - 'c/apache_mynewt/linux/mynewt_1_15_0_tag'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Clone matching private source branch
        env:
          GH_TOKEN: ${{ secrets.COMPILER_PAT }}
        shell: bash
        run: |
          set -euo pipefail
          gh repo clone "$GITHUB_REPOSITORY_OWNER/github_codespaces_compile" source -- --depth=1 --single-branch --branch "$GITHUB_REF_NAME"
      - name: Execute source script
        working-directory: source
        shell: bash
        run: |
          set -euo pipefail
          chmod +x -- 'c/apache_mynewt/linux/mynewt_1_15_0_tag/build.sh' 'tools/foundations/build_project.sh'
          './c/apache_mynewt/linux/mynewt_1_15_0_tag/build.sh'
