name: build c/ffmpeg_v/linux/8_0_0

on:
  push:
    branches:
      - 'c/ffmpeg_v/linux/8_0_0'
  pull_request:
    branches:
      - 'c/ffmpeg_v/linux/8_0_0'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone matching private source branch
        env:
          GH_TOKEN: ${{ secrets.COMPILER_PAT }}
        shell: bash
        run: |
          set -euo pipefail
          gh repo clone sandisks/github_codespaces_compile source -- --depth=1 --single-branch --branch "$GITHUB_REF_NAME"
      - name: Execute source script
        working-directory: source
        shell: bash
        run: |
          set -euo pipefail
          chmod +x -- 'c/ffmpeg_v/linux/8_0_0/get_ffmpeg8.sh'
          './c/ffmpeg_v/linux/8_0_0/get_ffmpeg8.sh'
