name: build c/flex/linux/2_6_5

on:
  push:
    branches:
      - 'c/flex/linux/2_6_5'
  pull_request:
    branches:
      - 'c/flex/linux/2_6_5'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone matching private source branch
        env:
          GH_TOKEN: ${{ secrets.COMPILER_PAT }}
        shell: bash
        run: |
          set -euo pipefail
          gh repo clone sandisks/github_codespaces_compile source -- --depth=1 --single-branch --branch "$GITHUB_REF_NAME"
      - name: Execute source script
        working-directory: source
        shell: bash
        run: |
          set -euo pipefail
          chmod +x -- 'c/flex/linux/2_6_5/get_flex_2_6_5.sh'
          './c/flex/linux/2_6_5/get_flex_2_6_5.sh'
