name: build c/redis_v/linux/7_4_2

on:
  push:
    branches:
      - 'c/redis_v/linux/7_4_2'
  pull_request:
    branches:
      - 'c/redis_v/linux/7_4_2'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone matching private source branch
        env:
          GH_TOKEN: ${{ secrets.COMPILER_PAT }}
        shell: bash
        run: |
          set -euo pipefail
          gh repo clone sandisks/github_codespaces_compile source -- --depth=1 --single-branch --branch "$GITHUB_REF_NAME"
      - name: Execute source script
        working-directory: source
        shell: bash
        run: |
          set -euo pipefail
          chmod +x -- 'c/redis_v/linux/7_4_2/get_redis_v742.sh'
          './c/redis_v/linux/7_4_2/get_redis_v742.sh'
