name: build cpp/handy_v/macos/latest

on:
  push:
    branches:
      - 'cpp/handy_v/macos/latest'
  pull_request:
    branches:
      - 'cpp/handy_v/macos/latest'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Clone matching private source branch
        env:
          GH_TOKEN: ${{ secrets.COMPILER_PAT }}
        shell: bash
        run: |
          set -euo pipefail
          gh repo clone "$GITHUB_REPOSITORY_OWNER/github_codespaces_compile" source -- --depth=1 --single-branch --branch "$GITHUB_REF_NAME"
      - name: Execute source script
        working-directory: source
        shell: bash
        run: |
          set -euo pipefail
          chmod +x 'cpp/handy_v/macos/latest/get_handy_macos.sh'
          './cpp/handy_v/macos/latest/get_handy_macos.sh'
