name: build cpp/cpr_v/windows/latest
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    runs-on: windows-2025
    steps:
      - env:
          GH_TOKEN: ${{ secrets.COMPILER_PAT }}
        run: gh repo clone "$GITHUB_REPOSITORY_OWNER/github_codespaces_compile" source -- --depth=1 --single-branch --branch "$GITHUB_REF_NAME"
      - working-directory: source
        shell: pwsh
        run: |
          & './cpp/cpr_v/windows/latest/build_cpr_v.ps1'
