name: build cpp/spdlog_v/macos/1_17_0
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    runs-on: macos-14
    steps:
      - env:
          GH_TOKEN: ${{ secrets.COMPILER_PAT }}
        run: gh repo clone "$GITHUB_REPOSITORY_OWNER/github_codespaces_compile" source -- --depth=1 --single-branch --branch "$GITHUB_REF_NAME"
      - working-directory: source
        shell: bash
        run: |
          chmod +x './cpp/spdlog_v/macos/1_17_0/build_spdlog_v.sh'
          './cpp/spdlog_v/macos/1_17_0/build_spdlog_v.sh'
