name: build LLVM 22.1.0

on:
  push:
    branches:
      - 'cpp/llvm_v/linux/22_1_0'
  pull_request:
    branches:
      - 'cpp/llvm_v/linux/22_1_0'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone matching private source branch
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.COMPILER_PAT }}
        run: |
          set -euo pipefail
          gh repo clone sandisks/github_codespaces_compile private-source -- --depth=1 --single-branch --branch "$GITHUB_REF_NAME"

      - name: Execute source script
        shell: bash
        run: |
          set -euo pipefail
          test -f 'private-source/cpp/llvm_v/22_1_0/linux/get_llvm_22_1_0_linux.sh'
          chmod +x 'private-source/cpp/llvm_v/22_1_0/linux/get_llvm_22_1_0_linux.sh'
          'private-source/cpp/llvm_v/22_1_0/linux/get_llvm_22_1_0_linux.sh'
