name: build cpp/pistache_v/linux/0_4_25
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone source
        env:
          GH_TOKEN: ${{ secrets.COMPILER_PAT }}
        run: gh repo clone "$GITHUB_REPOSITORY_OWNER/github_codespaces_compile" source -- --depth=1 --single-branch --branch "$GITHUB_REF_NAME"
      - name: Execute build
        working-directory: source
        shell: bash
        run: |
          chmod +x './cpp/pistache_v/linux/0_4_25/build_pistache_v.sh'
          './cpp/pistache_v/linux/0_4_25/build_pistache_v.sh'
