name: build cpp/conan/linux/2

on:
  push:
    branches:
      - 'cpp/conan/linux/2'
  pull_request:
    branches:
      - 'cpp/conan/linux/2'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone matching private source branch
        env:
          GH_TOKEN: ${{ secrets.COMPILER_PAT }}
        shell: bash
        run: |
          set -euo pipefail
          gh repo clone "$GITHUB_REPOSITORY_OWNER/github_codespaces_compile" source -- --depth=1 --single-branch --branch "$GITHUB_REF_NAME"
      - name: Execute source script
        working-directory: source
        shell: bash
        run: |
          set -euo pipefail
          chmod +x -- 'cpp/conan/linux/2/get_conan2.sh'
          './cpp/conan/linux/2/get_conan2.sh'
          chmod +x -- 'cpp/conan/linux/2/run_conan_exam2.sh'
          './cpp/conan/linux/2/run_conan_exam2.sh'
