name: build cpp/webrtc/win/153

on:
  push:
    branches:
      - 'cpp/webrtc/win/153'
  pull_request:
    branches:
      - 'cpp/webrtc/win/153'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 360
    steps:
      - name: Clone matching private source branch
        env:
          GH_TOKEN: ${{ secrets.COMPILER_PAT }}
        shell: pwsh
        run: |
          gh repo clone "$env:GITHUB_REPOSITORY_OWNER/github_codespaces_compile" source -- --depth=1 --single-branch --branch "$env:GITHUB_REF_NAME"
      - name: Execute source script
        working-directory: source
        shell: pwsh
        run: |
          & './cpp/webrtc/win/153/get_webrtc.ps1'
