name: build cpp/apache_arrow/linux/25_0_1

on:
  push:
    branches:
      - 'cpp/apache_arrow/linux/25_0_1'
  pull_request:
    branches:
      - 'cpp/apache_arrow/linux/25_0_1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:

      - name: Clone matching private source branch
        env:
          GH_TOKEN: ${{ secrets.COMPILER_PAT }}
        shell: bash
        run: |
          set -euo pipefail
          gh repo clone "$GITHUB_REPOSITORY_OWNER/github_codespaces_compile" source -- --depth=1 --single-branch --branch "$GITHUB_REF_NAME"
      - name: Execute source script
        working-directory: source
        shell: bash
        run: |
          set -euo pipefail
          chmod +x -- 'cpp/apache_arrow/linux/25_0_1/build.sh' 'tools/foundations/build_project.sh'
          './cpp/apache_arrow/linux/25_0_1/build.sh'
