name: build erlang/emqx/linux/6_3_1

on:
  push:
    branches:
      - 'erlang/emqx/linux/6_3_1'
  pull_request:
    branches:
      - 'erlang/emqx/linux/6_3_1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Set up Erlang toolchain
        uses: erlef/setup-beam@v1
        with:
          otp-version: '28.4.1'
          elixir-version: '1.19.1'
          rebar3-version: 'latest'
      - name: Clone matching private source branch
        env:
          GH_TOKEN: ${{ secrets.COMPILER_PAT }}
        shell: bash
        run: |
          set -euo pipefail
          gh repo clone "$GITHUB_REPOSITORY_OWNER/github_codespaces_compile" source -- --depth=1 --single-branch --branch "$GITHUB_REF_NAME"
      - name: Execute source script
        working-directory: source
        shell: bash
        run: |
          set -euo pipefail
          chmod +x -- 'erlang/emqx/linux/6_3_1/get_emqx.sh'
          './erlang/emqx/linux/6_3_1/get_emqx.sh'
