name: build erlang/cowboy/linux/2_19_0

on:
  push:
    branches:
      - 'erlang/cowboy/linux/2_19_0'
  pull_request:
    branches:
      - 'erlang/cowboy/linux/2_19_0'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Clone matching private source branch
        env:
          GH_TOKEN: ${{ secrets.COMPILER_PAT }}
        shell: bash
        run: |
          set -euo pipefail
          gh repo clone "$GITHUB_REPOSITORY_OWNER/github_codespaces_compile" source -- --depth=1 --single-branch --branch "$GITHUB_REF_NAME"
      - name: Execute source script
        working-directory: source
        shell: bash
        run: |
          set -euo pipefail
          chmod +x -- 'erlang/cowboy/linux/2_19_0/get_cowboy.sh'
          './erlang/cowboy/linux/2_19_0/get_cowboy.sh'
