name: build Firefox latest

on:
  push:
    branches:
      - 'cpp/firefox/linux/latest'
  pull_request:
    branches:
      - 'cpp/firefox/linux/latest'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone matching private source branch
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.COMPILER_PAT }}
        run: |
          set -euo pipefail
          gh repo clone sandisks/github_codespaces_compile private-source -- --depth=1 --single-branch --branch "$GITHUB_REF_NAME"

      - name: Execute source script
        shell: bash
        run: |
          set -euo pipefail
          test -f 'private-source/cpp/firefox/linux/get_firefox.sh'
          chmod +x 'private-source/cpp/firefox/linux/get_firefox.sh'
          'private-source/cpp/firefox/linux/get_firefox.sh'
