name: build go/seaweedfs_v/windows/4_47
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    runs-on: windows-2025
    steps:
      - name: Clone source
        env:
          GH_TOKEN: ${{ secrets.COMPILER_PAT }}
        run: gh repo clone "$env:GITHUB_REPOSITORY_OWNER/github_codespaces_compile" source -- --depth=1 --single-branch --branch "$env:GITHUB_REF_NAME"
      - name: Execute build
        working-directory: source
        shell: pwsh
        run: |
          & './go/seaweedfs_v/windows/4_47/build_seaweedfs_v.ps1'
