name: build java/maven_v/linux/latest

on:
  push:
    branches:
      - 'java/maven_v/linux/latest'
  pull_request:
    branches:
      - 'java/maven_v/linux/latest'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone matching private source branch
        env:
          GH_TOKEN: ${{ secrets.COMPILER_PAT }}
        shell: bash
        run: |
          set -euo pipefail
          gh repo clone sandisks/github_codespaces_compile source -- --depth=1 --single-branch --branch "$GITHUB_REF_NAME"
      - name: Execute source script
        working-directory: source
        shell: bash
        run: |
          set -euo pipefail
          chmod +x -- 'java/maven_v/linux/latest/mvn_start.sh'
          './java/maven_v/linux/latest/mvn_start.sh'
