name: build java/openjdk_v/linux/8

on:
  push:
    branches:
      - 'java/openjdk_v/linux/8'
  pull_request:
    branches:
      - 'java/openjdk_v/linux/8'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone matching private source branch
        env:
          GH_TOKEN: ${{ secrets.COMPILER_PAT }}
        shell: bash
        run: |
          set -euo pipefail
          gh repo clone "$GITHUB_REPOSITORY_OWNER/github_codespaces_compile" source -- --depth=1 --single-branch --branch "$GITHUB_REF_NAME"
      - name: Execute source script
        working-directory: source
        shell: bash
        run: |
          set -euo pipefail
          chmod +x -- 'java/openjdk_v/linux/8/download_openjdk8.sh'
          './java/openjdk_v/linux/8/download_openjdk8.sh'
