name: build python/pulp/linux/3_3_0

on:
  push:
    branches:
      - 'python/pulp/linux/3_3_0'
  pull_request:
    branches:
      - 'python/pulp/linux/3_3_0'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone matching private source branch
        env:
          GH_TOKEN: ${{ secrets.COMPILER_PAT }}
        shell: bash
        run: |
          set -euo pipefail
          gh repo clone sandisks/github_codespaces_compile source -- --depth=1 --single-branch --branch "$GITHUB_REF_NAME"
      - name: Execute source script
        working-directory: source
        shell: bash
        run: |
          set -euo pipefail
          chmod +x -- 'python/pulp/linux/3_3_0/get_python_pulp_linux_3_3_0.sh'
          './python/pulp/linux/3_3_0/get_python_pulp_linux_3_3_0.sh'
