name: build ruby/apache_attic_buildr/linux/1_5_8

on:
  push:
    branches:
      - 'ruby/apache_attic_buildr/linux/1_5_8'
  pull_request:
    branches:
      - 'ruby/apache_attic_buildr/linux/1_5_8'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Set up compatible Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: false
      - name: Clone matching private source branch
        env:
          GH_TOKEN: ${{ secrets.COMPILER_PAT }}
        shell: bash
        run: |
          set -euo pipefail
          gh repo clone "$GITHUB_REPOSITORY_OWNER/github_codespaces_compile" source -- --depth=1 --single-branch --branch "$GITHUB_REF_NAME"
      - name: Execute source script
        working-directory: source
        shell: bash
        run: |
          set -euo pipefail
          chmod +x -- 'ruby/apache_attic_buildr/linux/1_5_8/build.sh' 'tools/foundations/build_project.sh'
          './ruby/apache_attic_buildr/linux/1_5_8/build.sh'
