name: build Rust 1.80.0

on:
  push:
    branches:
      - 'rust/rust/linux/1_80_0'
  pull_request:
    branches:
      - 'rust/rust/linux/1_80_0'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone matching private source branch
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.COMPILER_PAT }}
        run: |
          set -euo pipefail
          gh repo clone sandisks/github_codespaces_compile private-source -- --depth=1 --single-branch --branch "$GITHUB_REF_NAME"

      - name: Execute source script
        shell: bash
        run: |
          set -euo pipefail
          test -f 'private-source/rust/rust/linux/1_80_0/get_rust_1_80_0.sh'
          chmod +x 'private-source/rust/rust/linux/1_80_0/get_rust_1_80_0.sh'
          'private-source/rust/rust/linux/1_80_0/get_rust_1_80_0.sh'
