name: build rust/mio/linux/1_1_1

on:
  push:
    branches:
      - 'rust/mio/linux/1_1_1'
  pull_request:
    branches:
      - 'rust/mio/linux/1_1_1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone matching private source branch
        env:
          GH_TOKEN: ${{ secrets.COMPILER_PAT }}
        shell: bash
        run: |
          set -euo pipefail
          gh repo clone "$GITHUB_REPOSITORY_OWNER/github_codespaces_compile" source -- --depth=1 --single-branch --branch "$GITHUB_REF_NAME"
      - name: Execute source script
        working-directory: source
        shell: bash
        run: |
          set -euo pipefail
          chmod +x -- 'rust/mio/linux/1_1_1/get_mio_1_1_1_linux.sh'
          './rust/mio/linux/1_1_1/get_mio_1_1_1_linux.sh'
