name: build rust/ripgrep_v/macos/latest
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Clone source
        env:
          GH_TOKEN: ${{ secrets.COMPILER_PAT }}
        run: gh repo clone "$GITHUB_REPOSITORY_OWNER/github_codespaces_compile" source -- --depth=1 --single-branch --branch "$GITHUB_REF_NAME"
      - name: Execute build
        working-directory: source
        shell: bash
        run: |
          chmod +x './rust/ripgrep_v/macos/latest/build_ripgrep_v.sh'
          './rust/ripgrep_v/macos/latest/build_ripgrep_v.sh'
